### ISSUE TITLE
Ambiguous keybase/twitter fields

### ISSUE THREAD

**Issue by wjdfx** [oasisprotocol/metadata-registry#14]
For entity-metadata.json file, I have seen some people submit different keybase and twitter fields. hope it is clear whether this is an address or a handle

```
{
  "v": 1,
  "serial": 1,
  "name": "My entity name",
  "url": "https://my.entity/url",
  "email": "my@entity.org",
  "keybase": "myentity",  #https://twitter.com/BitCat365 or BitCat365
  "twitter": "myentity"  #https://keybase.io/bitcat365 or FAB46CEEAEAB9FA1
}
```

**Comment by kostko** [comment]
So these are two separate issues, maybe they should be discussed in separate issues. Let's use this one for clarity around the twitter/keybase fields.

Regarding the keybase/twitter fields, [ADR 0001 specifies that these should be handles](https://github.com/oasisprotocol/metadata-registry/blob/production/docs/adr/0001-entity-metadata.md#entity-metadata-statements) and they are limited to 32 characters. We could add some additional validation in the tooling to make sure that this is really the case.

One easy way to do it is to restrict to only using alphanumeric characters, e.g. `[A-Za-z0-9]+` to prevent people from entering URLs. The existing non-conforming metadata statements could be then be removed from this registry.

**Comment by wjdfx** [comment]
This is reasonable, and hopefully soon, as more and more validators are submitting their information. 
Also we can explicitly add this hint in the [example](https://github.com/oasisprotocol/metadata-registry#contributing-new-statements), such as:

```
{
  "v": 1,
  "serial": 1,
  "name": "My entity name",
  "url": "https://my.entity/url",
  "email": "my@entity.org",
  "keybase": "myentity",  #keybase: a keybase.io handle (string, optional, max 32 characters)
  "twitter": "myentity" #twitter: a Twitter handle (string, optional, max 32 characters)
}
```

This is a simple function, may be nobody looks at [it](https://github.com/oasisprotocol/metadata-registry/blob/production/docs/adr/0001-entity-metadata.md#entity-metadata-statements) carefully,  We should remind them clearly.

**Comment by kostko** [comment]
Agreed, will update the README.

**Comment by kostko** [comment]
I've updated the specification and tooling. Invalid statements will be removed from the registry in #20 so affected entities should resubmit their statements.
