### ISSUE TITLE
Add logo field

### ISSUE THREAD

**Issue by wjdfx** [oasisprotocol/metadata-registry#16]
For some explorer and tools that need to direct display validator information, displaying logo is a very necessary function. Hope add logo field.

**Comment by Afauvre** [comment]
@kostko agree with the above. Would be great to set some template requirements including:
- 300x300 image requirement
- Inappropriate images will be removed

**Comment by kostko** [comment]
There is also the question of format and how the image is actually stored (embedded in the descriptor or is there only a hash in the descriptor and the image is in a separate file).

One option is also to just use Keybase or gravatar for images?

**Comment by wjdfx** [comment]
There are a lot of projects that use Keybase as the logo. looks like only use keybase user name to be enough.
I found just using keybase fields can realize this function, use keybase API:https://keybase.io/_/api/1.0/user/lookup.json?usernames=bitcat365
Let's try grab the images and save our database, apply to Oasis Scan.

**Comment by wjdfx** [comment]
We've found a way around this problem, using the Keybase username.
https://www.oasisscan.com/validators
